-- =====================================================================
-- SCRIPT DE CREACIÓN DE DATA WAREHOUSE PARA RUTA SUR S.A.
-- Base de Datos: Oracle 21g
-- =====================================================================

-- -----------------------------------------------------
-- 1. CREACIÓN DE LAS TABLAS DE DIMENSIÓN
-- -----------------------------------------------------

CREATE TABLE Dim_Tiempo (
    Tiempo_Key              INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    Fecha_Completa          DATE NOT NULL,
    Anio                    NUMBER(4) NOT NULL,
    Mes_Numero              NUMBER(2) NOT NULL,
    Mes_Nombre              VARCHAR2(20 CHAR) NOT NULL,
    Trimestre               NUMBER(1) NOT NULL,
    Dia_Semana              VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT pk_dim_tiempo PRIMARY KEY (Tiempo_Key)
);

CREATE TABLE Dim_Cliente (
    Cliente_Key             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Id_Cliente_OLTP         VARCHAR2(8 CHAR) NOT NULL,
    Nombre_Cliente          VARCHAR2(100 CHAR),
    Tipo_Cliente            VARCHAR2(20 CHAR),
    Ciudad_Cliente          VARCHAR2(100 CHAR),
    Region_Cliente          VARCHAR2(100 CHAR),
    CONSTRAINT pk_dim_cliente PRIMARY KEY (Cliente_Key)
);

CREATE TABLE Dim_Vehiculo (
    Vehiculo_Key            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Patente_Vehiculo_OLTP   VARCHAR2(8 CHAR) NOT NULL,
    Tipo_Vehiculo           VARCHAR2(30 CHAR),
    Modelo_Vehiculo         VARCHAR2(30 CHAR),
    Capacidad_Toneladas     NUMBER(5,2),
    CONSTRAINT pk_dim_vehiculo PRIMARY KEY (Vehiculo_Key)
);

CREATE TABLE Dim_Trabajador (
    Trabajador_Key              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Rut_Trabajador_OLTP         VARCHAR2(9 CHAR) NOT NULL,
    Nombre_Completo_Trabajador  VARCHAR2(80 CHAR),
    Tipo_Licencia               VARCHAR2(3 CHAR),
    CONSTRAINT pk_dim_trabajador PRIMARY KEY (Trabajador_Key)
);

CREATE TABLE Dim_Tipo_Trabajador (
    Tipo_Trabajador_Key     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre_Tipo_Trabajador  VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT pk_dim_tipo_trabajador PRIMARY KEY (Tipo_Trabajador_Key)
);

CREATE TABLE Dim_Tipo_Carga (
    Tipo_Carga_Key          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Id_Tipo_Carga_OLTP      VARCHAR2(8 CHAR) NOT NULL,
    Nombre_Tipo_Carga       VARCHAR2(30 CHAR),
    CONSTRAINT pk_dim_tipo_carga PRIMARY KEY (Tipo_Carga_Key)
);

CREATE TABLE Dim_Ruta (
    Ruta_Key                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Id_Ruta_Definida_OLTP   VARCHAR2(8 CHAR) NOT NULL,
    Nombre_Ruta             VARCHAR2(50 CHAR),
    Distancia_Estimada_KM   NUMBER(6),
    Nombre_Centro_Origen    VARCHAR2(50 CHAR),
    Ciudad_Origen           VARCHAR2(100 CHAR),
    Region_Origen           VARCHAR2(100 CHAR),
    Ciudad_Destino          VARCHAR2(100 CHAR),
    Zona_Destino            VARCHAR2(100 CHAR),
    Region_Destino          VARCHAR2(100 CHAR),
    Tipo_Destino            VARCHAR2(50 CHAR),
    CONSTRAINT pk_dim_ruta PRIMARY KEY (Ruta_Key)
);

-- -----------------------------------------------------
-- 2. CREACIÓN DE LAS TABLAS PUENTE (BRIDGE)
-- Para resolver las relaciones Muchos-a-Muchos.
-- -----------------------------------------------------

CREATE TABLE Bridge_Despacho_Trabajador (
    Despacho_Key            INTEGER NOT NULL,
    Trabajador_Key          INTEGER NOT NULL,
    Tipo_Trabajador_Key     INTEGER NOT NULL,
    CONSTRAINT pk_bridge_despacho_trabajador PRIMARY KEY (Despacho_Key, Trabajador_Key, Tipo_Trabajador_Key)
);

CREATE TABLE Bridge_Despacho_Carga (
    Despacho_Key            INTEGER NOT NULL,
    Tipo_Carga_Key          INTEGER NOT NULL,
    Peso_Transportado_TN    NUMBER(10, 2), -- La métrica del peso vive aquí ahora
    CONSTRAINT pk_bridge_despacho_carga PRIMARY KEY (Despacho_Key, Tipo_Carga_Key)
);

-- -----------------------------------------------------
-- 3. CREACIÓN DE LA TABLA DE HECHOS (FACT)
-- -----------------------------------------------------

CREATE TABLE Fact_Despachos (
    Despacho_Key                INTEGER GENERATED BY DEFAULT AS IDENTITY,
    -- Dimension Keys
    Tiempo_Key                  INTEGER NOT NULL,
    Cliente_Key                 INTEGER NOT NULL,
    Vehiculo_Key                INTEGER NOT NULL,
    Ruta_Key                    INTEGER NOT NULL,
    -- Degenerate Dimension
    Numero_Despacho_OLTP        VARCHAR2(8 CHAR),
    -- Measures
    Duracion_Estimada_Horas     NUMBER(10, 2),
    Duracion_Real_Horas         NUMBER(10, 2),
    Costo_Peaje_Estimado        NUMBER(12, 2),
    Costo_Peaje_Real            NUMBER(12, 2),
    Costo_Combustible_Real      NUMBER(12, 2),
    Otros_Costos_Real           NUMBER(12, 2),
    Costo_Total_Real            NUMBER(12, 2),
    CONSTRAINT pk_fact_despachos PRIMARY KEY (Despacho_Key)
);

-- -----------------------------------------------------
-- 4. CREACIÓN DE LAS RESTRICCIONES DE CLAVE FORÁNEA (FOREIGN KEYS)
-- -----------------------------------------------------

-- Foreign Keys para la tabla de Hechos
ALTER TABLE Fact_Despachos ADD CONSTRAINT fk_fact_tiempo FOREIGN KEY (Tiempo_Key) REFERENCES Dim_Tiempo(Tiempo_Key);
ALTER TABLE Fact_Despachos ADD CONSTRAINT fk_fact_cliente FOREIGN KEY (Cliente_Key) REFERENCES Dim_Cliente(Cliente_Key);
ALTER TABLE Fact_Despachos ADD CONSTRAINT fk_fact_vehiculo FOREIGN KEY (Vehiculo_Key) REFERENCES Dim_Vehiculo(Vehiculo_Key);
ALTER TABLE Fact_Despachos ADD CONSTRAINT fk_fact_ruta FOREIGN KEY (Ruta_Key) REFERENCES Dim_Ruta(Ruta_Key);

-- Foreign Keys para la tabla Puente de Trabajadores
ALTER TABLE Bridge_Despacho_Trabajador ADD CONSTRAINT fk_bridge_trab_despacho FOREIGN KEY (Despacho_Key) REFERENCES Fact_Despachos(Despacho_Key);
ALTER TABLE Bridge_Despacho_Trabajador ADD CONSTRAINT fk_bridge_trab_trabajador FOREIGN KEY (Trabajador_Key) REFERENCES Dim_Trabajador(Trabajador_Key);
ALTER TABLE Bridge_Despacho_Trabajador ADD CONSTRAINT fk_bridge_trab_tipotrab FOREIGN KEY (Tipo_Trabajador_Key) REFERENCES Dim_Tipo_Trabajador(Tipo_Trabajador_Key);

-- Foreign Keys para la tabla Puente de Carga
ALTER TABLE Bridge_Despacho_Carga ADD CONSTRAINT fk_bridge_carga_despacho FOREIGN KEY (Despacho_Key) REFERENCES Fact_Despachos(Despacho_Key);
ALTER TABLE Bridge_Despacho_Carga ADD CONSTRAINT fk_bridge_carga_tipocarga FOREIGN KEY (Tipo_Carga_Key) REFERENCES Dim_Tipo_Carga(Tipo_Carga_Key);

-- =====================================================================
-- FIN DEL SCRIPT
-- =====================================================================
